query GetUsers {
  users {
    id
    name
    email
    uid
  }
}


query GetUser {
  user(key: {uid:"fSK3JA9kOXPP8r7jKoZQRRQektB2"}) {
    id
    name
    email
    uid
  }
}


query GetNote  {
  note (id: "e09150f653aa4f7abfb81f0c9cd9ed87") {
    id
    title
    content
    createdAt
    updatedAt
    user {
      id
      name
      email
      uid
    }
  }
}

query GetNotes {
  notes {
    id
    title
    content
    createdAt
    updatedAt
    user {
      id
      name
      email
      uid
    }
  }
}


 

 query GeUserNotes{
  notes(where: { user: { id: { eq: "cbe1b7a742584a3892e9519f9a238ff7" } } }) {
    id
    title
    content
    createdAt
    updatedAt
    user {
      id
      name
      email
      uid
    }
  }
}