query GetUsers {
  users {
    id
    name
    email
    uid
  }
}


query GetUser {
  user(id: "6f30b8354dd54e73a0d67cf7d369c9bb" ) {
    id
    name
    email
    uid
  }
}


query GetNote  {
  note (id: "e09150f653aa4f7abfb81f0c9cd9ed87") {
    id
    title
    content
    createdAt
    updatedAt
    user {
      id
      name
      email
      uid
    }
  }
}

query GetNotes {
  notes {
    id
    title
    content
    createdAt
    updatedAt
    user {
      id
      name
      email
      uid
    }
  }
}